---
driver:
  name: vagrant
  

driver_config:
  require_chef_omnibus: true
  customize:
    memory: <%= 6*1024 %>
    cpus: 3
    
provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: centos-6.5
  - name: aws-ubuntu-12.04
    driver:
      name: ec2
      username: ubuntu
      image_id: ami-2f115c46
      flavor_id: m3.xlarge
      aws_access_key_id: <%= ENV['AWS_ACCESS_KEY'] %>
      aws_secret_access_key: <%= ENV['AWS_SECRET_KEY'] %>
      aws_ssh_key_id: <%= ENV['AWS_SSH_KEY_ID'] %>
      ssh_key: <%= File.expand_path("~/.ssh/#{ENV['AWS_SSH_KEY_ID']}") %>
      security_group_ids: ["default"]
      region: us-east-1
      availability_zone: us-east-1b
      ebs_optimized: false
  - name: aws-centos-6.5
    driver:
      name: ec2
      username: ec2-user
      image_id: ami-52009e3b
      flavor_id: m3.xlarge
      aws_access_key_id: <%= ENV['AWS_ACCESS_KEY'] %>
      aws_secret_access_key: <%= ENV['AWS_SECRET_KEY'] %>
      aws_ssh_key_id: <%= ENV['AWS_SSH_KEY_ID'] %>
      ssh_key: <%= File.expand_path("~/.ssh/#{ENV['AWS_SSH_KEY_ID']}") %>
      security_group_ids: ["default"]
      region: us-east-1
      availability_zone: us-east-1b      
      ebs_optimized: false

suites:
  - name: install
    run_list:
      - recipe[openstudio::default]
    attributes:  
      openstudio: 
        install_method: "installer"
  - name: build-ruby-2.0.0
    run_list:
      - recipe[openstudio::default]
    attributes:
      openstudio:
        version: <%= ENV['OS_BUILD_VERSION'].nil? ? '1.3.2' : ENV['OS_BUILD_VERSION'].inspect %>
        install_method: "source"
        source:
          version: <%= ENV['OS_DOWNLOAD_VERSION'].nil? ? 'v1.3.2' : ENV['OS_DOWNLOAD_VERSION'].inspect %>
          version_revision: <%= ENV['OS_BUILD_VERSION_REVISION'].nil? ? '386caf0e00' : ENV['OS_BUILD_VERSION_REVISION'].inspect %>
          build_prefix: "/mnt"
        ruby:
          version: '2.0.0-p451'
  - name: build-ruby-2.1.1
    run_list:
      - recipe[openstudio::default]
    attributes:
      openstudio:
        version: <%= ENV['OS_BUILD_VERSION'].nil? ? '1.3.2' : ENV['OS_BUILD_VERSION'].inspect %>
        install_method: "source"
        source:
          version: <%= ENV['OS_DOWNLOAD_VERSION'].nil? ? 'v1.3.2' : ENV['OS_DOWNLOAD_VERSION'].inspect %>
          version_revision: <%= ENV['OS_BUILD_VERSION_REVISION'].nil? ? '386caf0e00' : ENV['OS_BUILD_VERSION_REVISION'].inspect %>
          build_prefix: "/mnt"
        ruby:
          version: '2.1.1'
